const weatherCodes = new Map
weatherCodes.set(0, "clear sky")
weatherCodes.set(1, "mainly clear")
weatherCodes.set(2, "partly cloudy")
weatherCodes.set(3, "overcast")
weatherCodes.set(45, "fog")
weatherCodes.set(48, "depositing rime fog")
weatherCodes.set(51, "light drizzle")
weatherCodes.set(53, "moderate drizzle")
weatherCodes.set(55, "dense drizzle")
weatherCodes.set(56, "light freezing drizzle")
weatherCodes.set(57, "dense freezing drizzle")
weatherCodes.set(61, "slight rain")
weatherCodes.set(63, "moderate rain")
weatherCodes.set(65, "heavy rain")
weatherCodes.set(66, "light freezing rain")
weatherCodes.set(67, "heavy freezing rain")
weatherCodes.set(71, "slight snow fall")
weatherCodes.set(73, "moderate snow fall")
weatherCodes.set(75, "heavy snow fall")
weatherCodes.set(77, "snow grains")
weatherCodes.set(80, "slight rain showers")
weatherCodes.set(81, "moderate rain showers")
weatherCodes.set(82, "violent rain showers")
weatherCodes.set(85, "slight snow showers")
weatherCodes.set(86, "heavy snow showers")
weatherCodes.set(95, "thunderstorm")
weatherCodes.set(96, "thunderstorm with slight hail")
weatherCodes.set(99, "thunderstorm with heavy hail")

export { weatherCodes }